In [14]:
import numpy as np
from tqdm import tqdm_notebook as tqdm
import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as opt

In [15]:
N = 100
total=np.zeros((1,5))
faulty = []
for i in range(N):
    try:
        test=np.loadtxt('FTSteane_3rd_a/FTSteane_3rd_a{}.txt'.format(i),delimiter=',')
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    total=total+test
total = total/N
print("Dead files: ", faulty)
N = print(total)

Dead files:  []
[[0.000e+00 5.000e-03 1.000e-02 1.500e-02 2.000e-02]
 [0.000e+00 5.500e-02 9.950e-02 1.495e-01 1.960e-01]
 [0.000e+00 9.450e-01 9.005e-01 8.505e-01 8.040e-01]
 [9.995e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [5.000e-04 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 5.050e-02 1.035e-01 1.605e-01 2.040e-01]
 [0.000e+00 9.490e-01 8.965e-01 8.395e-01 7.960e-01]
 [9.990e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [1.000e-03 5.000e-04 0.000e+00 0.000e+00 0.000e+00]]


In [16]:
#np.savetxt('text/Carbon_3rd_4.txt', total, delimiter=",")
#np.savetxt('text/RotSurf_3rd_f.txt', total, delimiter=",")
np.savetxt('text/FTSteane_3rd_a.txt', total, delimiter=",")