In [5]:
import numpy as np
from tqdm import tqdm_notebook as tqdm
import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as opt

In [6]:
N = 80
total=np.zeros((1,5))
faulty = []
for i in range(N):
    try:
        test=np.loadtxt('FTSteane_3rd_c/FTSteane_3rd_c{}.txt'.format(i),delimiter=',')
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    total=total+test
total = total/N
print("Dead files: ", faulty)
N = print(total)

Dead files:  []
[[0.00000e+00 2.50000e-04 5.00000e-04 7.50000e-04 1.00000e-03]
 [0.00000e+00 3.12500e-03 1.87500e-03 1.00000e-02 1.00000e-02]
 [0.00000e+00 5.56250e-01 7.73750e-01 8.81875e-01 9.36875e-01]
 [9.98750e-01 3.94375e-01 1.75000e-01 7.12500e-02 3.37500e-02]
 [1.25000e-03 4.62500e-02 4.93750e-02 3.68750e-02 1.93750e-02]
 [0.00000e+00 6.25000e-04 3.12500e-03 8.75000e-03 1.56250e-02]
 [0.00000e+00 3.18750e-02 7.37500e-02 9.87500e-02 1.40000e-01]
 [9.98750e-01 7.43750e-01 5.81875e-01 5.07500e-01 4.40000e-01]
 [1.25000e-03 2.23750e-01 3.41250e-01 3.85000e-01 4.04375e-01]]


In [7]:
#np.savetxt('text/Carbon_3rd_4.txt', total, delimiter=",")
#np.savetxt('text/RotSurf_3rd_f.txt', total, delimiter=",")
np.savetxt('text/FTSteane_3rd_c.txt', total, delimiter=",")