In [2]:
import numpy as np
from tqdm import tqdm_notebook as tqdm
import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as opt

In [5]:
N = 100
total=np.zeros((1,4))
faulty = []
for i in range(N):
    try:
        test=np.loadtxt('FTSteane_3rd_e/FTSteane_3rd_e{}.txt'.format(i),delimiter=',')
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    total=total+test
total = total/(N-len(faulty))
print("Dead files: ", faulty)
N = print(total)

Dead files:  []
[[2.500e-04 5.000e-04 7.500e-04 1.000e-03]
 [3.500e-03 2.000e-03 1.050e-02 1.200e-02]
 [5.160e-01 7.805e-01 8.875e-01 9.295e-01]
 [4.285e-01 1.705e-01 7.300e-02 3.550e-02]
 [5.200e-02 4.700e-02 2.900e-02 2.300e-02]
 [1.000e-03 9.000e-03 8.500e-03 1.150e-02]
 [3.740e-01 6.135e-01 7.565e-01 8.620e-01]
 [5.545e-01 3.095e-01 1.715e-01 9.200e-02]
 [7.050e-02 6.800e-02 6.350e-02 3.450e-02]]


In [6]:
#np.savetxt('text/Carbon_3rd_4.txt', total, delimiter=",")
#np.savetxt('text/RotSurf_3rd_f.txt', total, delimiter=",")
np.savetxt('text/FTSteane_3rd_e.txt', total, delimiter=",")