In [1]:
import numpy as np
from tqdm import tqdm_notebook as tqdm
import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as opt

In [2]:
N = 100
total=np.zeros((1,5))
faulty = []
for i in range(N):
    try:
        test=np.loadtxt('FTSteane_3rd_b/FTSteane_3rd_b{}.txt'.format(i),delimiter=',')
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    total=total+test
total = total/N
print("Dead files: ", faulty)
N = print(total)

Dead files:  []
[[0.000e+00 2.500e-04 5.000e-04 7.500e-04 1.000e-03]
 [0.000e+00 5.000e-03 5.000e-03 1.000e-02 8.000e-03]
 [0.000e+00 5.150e-01 7.630e-01 8.720e-01 9.370e-01]
 [9.985e-01 4.145e-01 1.780e-01 8.400e-02 3.550e-02]
 [1.500e-03 6.550e-02 5.400e-02 3.400e-02 1.950e-02]
 [0.000e+00 2.000e-03 4.500e-03 1.200e-02 1.100e-02]
 [0.000e+00 3.220e-01 5.375e-01 6.755e-01 7.595e-01]
 [1.000e+00 5.545e-01 3.015e-01 1.885e-01 1.285e-01]
 [0.000e+00 1.215e-01 1.565e-01 1.240e-01 1.010e-01]]


In [3]:
#np.savetxt('text/Carbon_3rd_4.txt', total, delimiter=",")
#np.savetxt('text/RotSurf_3rd_f.txt', total, delimiter=",")
np.savetxt('text/FTSteane_3rd_b.txt', total, delimiter=",")